language: go
sudo: required
go:
  - 1.14.2
install: true

services:
  - docker

before_install:
  - docker pull gomesh/mock-pilot:latest
  - docker run -d -p 15010:15010 gomesh/mock-pilot:latest

before_script:
  - mkdir -p $HOME/gopath/src/github.com/apache/servicecomb-mesher
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/apache/servicecomb-mesher
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/apache/servicecomb-mesher
  - export KUBE_CONFIG=$HOME/gopath/src/github.com/apache/servicecomb-mesher/tests/util/sample_kubeconfig
  - cd $HOME/gopath/src/github.com/apache/servicecomb-mesher
jobs:
  include:
    - stage: Format Checker
      script: bash -x scripts/travis/formatChecker.sh
    - arch: arm64
      script: bash -x scripts/travis/formatChecker.sh
    - stage: DeadCode Checker
      script:
        - go get -u github.com/tsenart/deadcode
        - bash -x scripts/travis/deadCodeChecker.sh
    - arch: arm64
      script:
        - go get -u github.com/tsenart/deadcode
        - bash -x scripts/travis/deadCodeChecker.sh
    - stage: Misspell Checker
      script:
        - go get -u github.com/client9/misspell
        - bash -x scripts/travis/misspellChecker.sh
    - arch: arm64
      script:
        - go get -u github.com/client9/misspell
        - bash -x scripts/travis/misspellChecker.sh
    - stage: GoConst Checker
      script:
        - go get -u github.com/jgautheron/goconst/cmd/goconst
        - bash -x scripts/travis/goConstChecker.sh
    - arch: arm64
      script:
        - go get -u github.com/jgautheron/goconst/cmd/goconst
        - bash -x scripts/travis/goConstChecker.sh
    - stage: GoLint Checker
      script:
        - go get -u golang.org/x/lint/golint
        - bash -x scripts/travis/goLintChecker.sh
    - arch: arm64
      script:
        - go get -u golang.org/x/lint/golint
        - bash -x scripts/travis/goLintChecker.sh
    - stage: GoCyclo Checker
      script:
        - go get github.com/fzipp/gocyclo
        - bash -x scripts/travis/goCycloChecker.sh
    - arch: arm64
      script:
        - go get github.com/fzipp/gocyclo
        - bash -x scripts/travis/goCycloChecker.sh
    - stage: GoSecure Checker
      script:
        - go get github.com/securego/gosec/cmd/gosec
        - bash -x scripts/travis/goSecureChecker.sh
    - arch: arm64
      script:
        - go get github.com/securego/gosec/cmd/gosec
        - bash -x scripts/travis/goSecureChecker.sh
    - stage: Build
      script: 
        - GO111MODULE=on go mod download
        - go build github.com/apache/servicecomb-mesher/cmd/mesher
    - arch: arm64
      script:
        - GO111MODULE=on go mod download
        - go build github.com/apache/servicecomb-mesher/cmd/mesher
    - stage: Unit Test
      script:
        - go get github.com/mattn/goveralls
        - go get golang.org/x/tools/cmd/cover
        - GO111MODULE=on go mod download
        - bash -x scripts/travis/unit_test.sh && $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci
    - arch: arm64
      script:
        - go get github.com/mattn/goveralls
        - go get golang.org/x/tools/cmd/cover
        - GO111MODULE=on go mod download
        - bash -x scripts/travis/unit_test.sh && $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci
