## microservice property
APPLICATION_ID: mesher
service_description:
  name: hellomesher
  version: 0.0.1
  environment:  #microservice environment
  properties:
    allowCrossApp: false #whether to allow calls across applications
